# ________________________________________________
#
#      MINIO LANGUAGE FILE
#
# Here you can customise Bot's Messages.
#
# ________________________________________________

general:
  cmd_disabled: "This command is disabled on this server."
  cannot_staff: "That User is Staff Member."
  cannot_self: "You cannot do that on yourself."
  cannot_bot: "You cannot do that on Bot"
  higher_perm: "That User has higher permission than me."
  no_perm: "You don't have permission to perform this command."
  msgid: "You have entered Invalid Message ID"
  # Valid Placeholders: <role>
  no_role: "You need <role> Role to use this command."
  not_set: "You don't have that option set so it cannot be reseted."
  invalid_usage: "Invalid Usage of Command. Usage: <usage>"
  lb_empty: "This Leaderboard Type is empty"
  ping_loading: "Ping.."
  ping: "Bot Uptime is <uptime>, bot ping <bot>ms, api ping <api>ms"
  help_format: "\n> `<prefix><usage>` - <description>, "
  auto_response: "Hey <user>, <response>."
  auto_announce: "<message>."
  cooldown: "You're on cooldown for next <cooldown>."
  starboard:
    author: "<user>・⭐ <stars>"
    description: "**Message:**\n\n>>> <message>\n\n[Click Here to go to Message](<link>)"
    # Must be set
    footer: "Message ID: "
  suggestions:
    accepted: "Suggestion have been accepted successfully"
    denied: "Suggestion have been denied successfully"
    deleted: "Suggestion have been deleted successfully"
    sent: "Your Suggestion have been successfully sent."
    vote_yes: "You have UpVoted this Suggestion."
    vote_no: "You have DownVoted this Suggestion."
    vote_reset: "Your Vote have been reseted."
    decision_yes: "Suggestion have been approved"
    decision_no: "Suggestion have been denied."
    placeholder: "Select decision option for this Suggestion"
    decision:
      accept: "Accept Suggestion"
      deny: "Deny Suggestion"
      delete: "Delete Suggestion"
    not_voted: "You cannot reset Vote because you didn't vote."
    already_voted: "You have already voted, please reset your Vote"
  no_suggest: "No suggestion channel have been setuped, suggestion cannot be sent."
  verify_placeholder: "Select option with label <code>"
  dm_closed: "<user>, your DM's closed, enable them and then try reverify using `verify` command"
  rps_request: "Hey <user>, <author> has challenged you on for Rock, Paper, Scissors game, if you want to play accept request."
  rps_start: "Rock, Paper, Scissors Game has started, please select your choices."
  rps_won: "Player <winner> (<winnerChoice>) has won RPS against <loser> (<loserChoice>)."
  rps_expired: "RPS option wasn't choose in time, game won't start."
  rps_denied: "<player> has denied RPS game."
  rps_chose: "You chose the <option> in rps game."
  rps_already: "You or other player are already in an RPS game."
buttons:
  next: "Next"
  previous: "Previous"
  yes_vote: "Yes"
  no_vote: "No"
  remove_vote: "Remove Vote"
  giveaway:
    start: "Yes, Start Giveaway"
    cancel: "No, don't Start Giveaway"
  leaderboard:
    next: "Next Page"
    previous: "Previous Page"
  rps:
    rock: "Rock"
    paper: "Paper"
    scissors: "Scissors"
    yes: "Accept RPS"
    no: "Deny RPS"
titles:
  error: "Error"
  invites_top: "Invites Leaderboard"
  messages_top: "Messages Leaderboard"
  level_top: "Level Leaderboard"
  balance_top: "Balance Leaderboard"
  levelup: "Level UP"
  invites: "Invites"
  auto_announce: "Auto Announcement"
  auto_response: "Auto Response"
  sugg_accepted: "Suggestion accepted"
  sugg_denied: "Suggestion denied"
  logs:
    channel_delete: "Channel Delete"
    channel_create: "Channel Create"
    message_delete: "Message Removed"
    message_update: "Message Updated"
    member_update: "Member Updated"
    guild_update: "Guild Updated"
    role_create: "Role Created"
    role_delete: "Role Deleted"
    role_update: "Role Updated"
    voice_update: "Voice Update"
    fields:
      user: "User"
      staff: "Staff"
      reason: "Reason"
      duration: "Duration"
      warns: "Warnings"
  help:
    general: "Main Menu"
    member: "Member Category"
    economy: "Economy Category"
    utility: "Utility Category"
    mod: "Moderation Category"
    music: "Music Category"
    fun: "Fun Category"
    giveaway: "Giveaway Category"
    placeholder: "Choose Command Category"
  shop: "Browse Shop"
  infractions: "<user>'s Infractions"
  birthdays: "Today's Birthdays"
  birthdays_mon: "Upcoming Birthdays"
modals:
  placeholders:
    suggestion: "Enter Text of your Suggestion"
    calculate: "Calculate"
  labels:
    suggestion: "Suggestion Text"
    calculate: "Calculation Expression"
utility:
  getid: "ID of <type> is `<id>`."
  no_text: "You haven't provided text for suggestion"
  counters_started: "Counters have started creating, please wait."
  counters_created: "Counters have been created."
  total_counter: "Total Members: <stats>"
  members_counter: "Members: <stats>"
  robots_counter: "Bots: <stats>"
  channels_counter: "Channels: <stats>"
  roles_counter: "Roles: <stats>"
  boosts_counter: "Boosts: <stats>"
  counters_category: "Server Statistics"
  math_error: "An Error occurred during calculation."
  no_desc: "You need to provide embed description."
  verify_channel: "You cannot ReVerify in this channel."
member:
  titles:
    avatar: "Avatar"
  avatar: "<user>'s Avatar"
  levelup: "Congratulations <user>, you've advanced to <level> level."
  invalid_date: "You have provided Invalid Date format, ex. 18 Jan 2000 / 18.1.2000"
  bday_set: "Your birthday have been set to `<date>`."
  bday_ann: "Hey! We got birthdays today, send congratulations to following users:\n\n<birthdays>"
  bday_reset: "Your birthday have been reseted successfully."
  no_bday: "You don't have birthday set so you can't reset it."
  bday_list_empty: "No Birthdays this month"
  invalid_time: "You have entered invalid time."
  reminder_action: "You have entered invalid action, valid actions: add, cancel, list"
  reminder_added: "You have added reminder for <reason> that will trigger in <time>."
  reminder_id: "You didn't specify reminder id to cancel."
  reminder_canceled: "Reminder with ID **#<id>** have been canceled."
  reminder_empty: "You don't have any reminder added."
  reminder_invalid: "You have entered invalid reminder ID"
  reminder_list: "List of your active reminders:\n<reminders>"
  reminder: "Hey <user>, I'm here to remind you of\n```<reason>```"
invites:
  # Valid Placeholders <user>
  joinHistory: "[ 📥 ] **<user>** has **joined** server."
  leaveHistory: "[ 📤 ] **<user>** has **left** server."
  invites: "<user> has <regularInvites> invites (<joinsInvites> joins, <leavesInvites> leaves)\nRank: #<rank>"
temporary:
  # Name of Temporary Channel
  # Valid Placehodlers: <user>
  temp_name: "🔒〡<user>"
backup:
  title: "Backup"
  started: "Backup creation has started, please wait..."
  done: "Backup has finished creating, load it using loadbackup <id>"
  loading: "Backup with ID <id> has started loading.."
  invalid_id: "Backup with ID <id> couldn't be found."
economy:
  title: "Economy"
  worked: "You have worked as <job> and earned salary of $<salary>."
  # Valid Placeholders: <balance>, <bank>, <total>
  balance: "<user>'s total balance is $<total> ($<bank> in bank, $<balance> in wallet)."
  daily:
    already: "You have already claimed your daily reward today, try again tomorrow."
    claimed: "You have successfully claimed your daily reward and got $<daily>."
  bet:
    cooldown: "You're on cooldown for betting"
    less: "You cannot bet less than $100"
    won: "You have betted <amount> and won."
    lost: "You have betted <amount> and lost."
  no_enough: "You don't have enough money."
  invalid_amount: "You have entered invalid amount."
  payed: "You have payed $<amount> to <user>"  
  bank:
    deposited: "You have deposited $<amount> into your bank. Total amount in bank now $<bank>"
    withdrawed: "You have withdrawed $<amount> from bank. Total amount in bank now $<bank>"
  purchased: "You have successfully purchased <item> for $<price>."
  rob_fail: "You have tried to rob <user> but police caught you and fined you $<amount>."
  rob_success: "You have successfully robbed <user> and got away with $<amount>"
  rob_no_money: "You or user that you're trying to rob doesn't have $<minimum>."
  slots_won: "You have won in slots game and earned $<amount>.\n\n<columns>"
  slots_lost: "You have lost in slots game and lost $<amount>.\n\n<columns>"
  slots_row: "> `<firstItem> | <secondItem> | <thirdItem>`"
  slots_win_row: "> `<firstItem> | <secondItem> | <thirdItem>`"
moderation:
  titles:
    clear: "Messages Purged"
    ban: "Ban"
    tempban: "Temporary Ban"
    kick: "Kick"
    mute: "Mute"
    warn: "Warn"
    unban: "Unban"
    unmute: "UnMute"
    unwarn: "UnWarn"
    slowmode: "Slowmode"
  history:
    format: "[<date>] <user> have been <punishment> by <staff>, reason: <reason> (<duration>)"
    banned: "banned"
    muted: "muted"
    warned: "warned"
    kicked: "kicked"
    temp: "temporary"
    empty: "History of this user is empty."
  purged: "Purged a total of <count> messages(s) from channel."
  invalid_count: "You cannot purge more than 100 & less than 1 message."
  invalid_duration: "You've entered Invalid Duration for Mute, ex. 30min"
  no_reason: "No Reason Provided"
  reason_long: "Reason is too long."
  already_muted: "User is already muted."
  not_banned: "That User isn't banned."
  not_muted: "That User isn't muted."
  slowmode: "Slowmode for Channel <channel> have been changed to <seconds> seconds."
  no_warns: "That User doesn't have any warnings"
  banned: "<user> have been banned by <staff> for <reason>."
  tempbanned: "<user> have been temporary banned by <staff> for <reason>, for duration of <duration>."
  muted: "<user> have been muted by <staff> for <reason>, for duration of <duration>."
  warned: "<user> have been Warned by <staff> for <reason>"
  kicked: "<user> have been kicked by <staff> for <reason>."
  unbanned: "<user> have been unbanned by <staff>"
  unmuted: "<user> have been UnMuted by <staff>"
  unwarned: "<user> have been UnWarned by <staff> and now has <warns>"
  role_added: "Role <role> have been assigned to <user>"
  role_removed: "Role <role> have been removed from <user>"
  have_role: "User <user> already has the role <role> so it can't be given to him"
  dont_have_role: "User <user> doesn't have Role <role> so it cannot be removed."
  cannot_add: "You cannot give that role to that member."
  cannot_remove: "You cannot remove that role from that member."
music:
  title: "Music"
  no_song: "There aren't songs playing."
  stopped: "Music has stopped."
  empty: "Queue is empty."
  skipped: "Song have been skipped."
  need_three: "3 Songs in queue are required for queue to be shuffled"
  shuffled: "Queue have been shuffled."
  not_paused: "Queue isn't paused."
  already_paused: "Song is already paused."
  paused: "Song have been paused."
  resumed: "Queue have been resumed."
  cannot_find: "Cannot find Song with that ID."
  removed: "Song with ID `<number>` have been removed from queue."
  play:
    not_found: "No song were found with query `<song>`."
    searching: "Searching for `<song>`."
    cannot_join: "Cannot join Voice Channel."
    not_voice: "You're not in Voice Channel."
    diff_voice: "Bot is playing in different Voice Channel."
    pl_playing: "Playlist **<title>** by **<author>** have started playing."
    pl_added: "Playlist **<title>** by **<author>** have been added to queue."
    song_playing: "Song **<title>** by **<author>** have started playing."
    song_added: "Song **<title>** by **<author>** have been added to queue."
  volume:
    current: "Current volume is **<volume>%**"
    limit: "Volume cannot be higher than 200% and lower than 0%"
    changed: "Volume have been changed to `<volume>%`."
  queue:
    song_loop: "Song Loop have been enabled."
    queue_loop: "Queue Loop have been enabled."
    loop_disabled: "Loop have been disabled."
    status: "Current Loop Status - <status>"
giveaway:
  titles:
    giveaway: "Giveaway"
    setup: "Giveaway Setup"
    ended: "Giveaway Ended"
    edit: "Edit Giveaway"
    entry: "Giveaway Entry"
  ended: "Giveaway have been ended successfuly."
  create:
    already_started: "You have already started giveaway creation, finish it first."
    expired: "Time has passed without answer, creation have been stopped."
    canceled: "Giveaway creation have been canceled."
    duration: "Enter Duration for Giveaway.\nExample: `2m`"
    channel: "Mention Channel in which to start Giveaway.\nExample: `#general`"
    winners: "Enter number of Winners for Giveaway.\nExample: `3`"
    messages: "Enter number of Messages required to enter Giveaway, 0 for none.\nExample: `150`"
    invites: "Enter number of Invites required to enter Giveaway, 0 for none.\nExample: `10`"
    prize: "Enter Prize for Giveaway.\nExample: `Discord Nitro`"
    done: "Giveaway has started in channel <channel>"
    extra_time: "Enter Extra-Time for Giveaway.\nExample `2m`"
    errors:
      channel: "You have mentioned Invalid Channel"
      winners: "You have entered Invalid Number of Winners"
      messages: "You have entered Invalid Number of Messages"
      invites: "You have entered Invalid Number of Invites"
      prize: "You have entered Invalid Prize"
  edit:
    done: "Giveaway have been edited successfully."
    finish: "You have successfully finished Editing of Giveaway."
  embed:
    requirements: "\n\nRequirements:"
    messages: "\n - You need <messages> messages to enter Giveaway."
    invites: "\n - You need <invites> invites to enter Giveaway."
    winners_yes: "Congratulations to winner(s) <winners> on winng this giveaway."
    winners_no: "Giveaway has ended without winners."
    reroll: "New winners are <winners>"
    ends: "Ends At"
    ended: "Ended"
    winners: "\nWinners: <winenrs>"
    without_winners: "No Winners"
  entry_approved: "Your Giveaway Entry in <guild> have been approved (<prize>)"
  entry_denied: "Your Giveaway Entry in <guild> have been denied (<prize>)"
  not_meet: "You don't meet requirements for this giveaway:"
reaction_roles:
  invalid_category: "You have entered Invalid Category ID for Reaction Role"
  created: "Reaction Role <category> have been created."
administration:
  level_added: "<level> levels have been added to <user> who now have total of <total> levels."
  level_removed: "<level> levels have been removed from <user> who now have total of <total> levels."
  money_added: "$<money> have been added to <user>'s <type> who now have total of $<total>."
  money_removed: "$<money> have been removed from <user>'s <type> who now have total of $<total>."
  xp_added: "<xp> XP have been added to <user> who now have total of <total> XP."
  xp_removed: "<xp> XP have been removed from <user> who now have total of <total> XP."